version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - WOFF2_SERVER=http://woff2:8080/woff2
      - CDN_URL=https://play.min.io:9000/result-font
      - S3_ENDPOINT=https://play.min.io:9000
      - S3_AK=Q3AM3UQ867SPQQA43P2F
      - S3_SK=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      - S3_REGION=us-east-1
  woff2:
    build: ./server/woff2
    expose:
      - "8080"
