/* automatically generated by proto-to-cli */
use clap::Parser;
use std::path::PathBuf;
#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
#[clap(name = "InputTemplate")]
pub struct InputTemplate {
    #[arg(
        long = "input",
        short = 'i',
        help = "ttf 文件的 buffer"
    )]
    pub input: PathBuf,

    #[arg(
        long = "outDir",
        short = 'o',
        help = "切割后放置文件的文件夹"
    )]
    pub out_dir: Option<String>,

    #[arg(
        long = "css.fontFamily",
        help = "字体家族名称"
    )]
    pub css_font_family: Option<String>,

    #[arg(
        long = "css.fontWeight",
        help = "字体粗细"
    )]
    pub css_font_weight: Option<String>,

    #[arg(
        long = "css.fontStyle",
        help = "字体样式"
    )]
    pub css_font_style: Option<String>,

    #[arg(
        long = "css.fontDisplay",
        help = "字体显示方式"
    )]
    pub css_font_display: Option<String>,

    #[arg(
        long = "css.localFamily",
        help = "本地字体家族名称"
    )]
    pub css_local_family: Option<Vec<String>>,

    #[arg(
        long = "polyfill.name",
        help = "名称"
    )]
    pub polyfill_name: Option<String>,

    #[arg(
        long = "polyfill.format",
        help = "格式"
    )]
    pub polyfill_format: Option<String>,

    #[arg(
        long = "css.commentBase",
        help = "基础注释"
    )]
    pub css_comment_base: Option<bool>,

    #[arg(
        long = "css.commentNameTable",
        help = "名称表注释"
    )]
    pub css_comment_name_table: Option<bool>,

    #[arg(
        long = "css.commentUnicodes",
        help = "Unicode 注释"
    )]
    pub css_comment_unicodes: Option<bool>,

    #[arg(
        long = "css.compress",
        help = "是否压缩"
    )]
    pub css_compress: Option<bool>,

    #[arg(
        long = "css.fileName",
        help = "文件名"
    )]
    pub css_file_name: Option<String>,

    #[arg(
        long = "targetType",
        short = 't',
        help = "目标类型"
    )]
    pub target_type: Option<String>,

    #[arg(
        long = "subsets",
        short = 's',
        help = "子集"
    )]
    pub subsets: Vec<PathBuf>,

    #[arg(
        long = "chunkSize",
        short = 'c',
        help = "包大小"
    )]
    pub chunk_size: Option<i32>,

    #[arg(
        long = "chunkSizeTolerance",
        help = "包大小容差"
    )]
    pub chunk_size_tolerance: Option<f32>,

    #[arg(
        long = "maxAllowSubsetsCount",
        short = 'm',
        help = "最大允许子集数量"
    )]
    pub max_allow_subsets_count: Option<i32>,

    #[arg(
        long = "testHtml",
        help = "是否生成测试 HTML"
    )]
    pub test_html: Option<bool>,

    #[arg(
        long = "reporter",
        short = 'r',
        help = "是否生成 reporter.bin"
    )]
    pub reporter: Option<bool>,

    #[arg(
        long = "previewImage.text",
        help = "会显示在 svg 中的文本"
    )]
    pub preview_image_text: Option<String>,

    #[arg(
        long = "previewImage.name",
        help = "svg 文件的名称"
    )]
    pub preview_image_name: Option<String>,

    #[arg(
        long = "renameOutputFont",
        help = "重命名输出字体"
    )]
    pub rename_output_font: Option<String>,

    #[arg(
        long = "buildMode",
        short = 'b',
        help = "TODO 构建模式"
    )]
    pub build_mode: Option<String>,

    #[arg(
        long = "languageAreas",
        short = 'l',
        help = "是否进行语言区域优化"
    )]
    pub language_areas: Option<bool>,

    #[arg(
        long = "multiThreads",
        help = "TODO 是否使用多线程"
    )]
    pub multi_threads: Option<bool>,

    #[arg(
        long = "fontFeature",
        short = 'f',
        help = "是否启用字体特性"
    )]
    pub font_feature: Option<bool>,

    #[arg(
        long = "reduceMins",
        help = "是否减少最小分包，"
    )]
    pub reduce_mins: Option<bool>,

    #[arg(
        long = "autoSubset",
        short = 'a',
        help = "是否自动子集化"
    )]
    pub auto_subset: Option<bool>,

    #[arg(
        long = "subsetRemainChars",
        help = "是否自动添加没有声明的字符"
    )]
    pub subset_remain_chars: Option<bool>,

}