use crate::runner::Context;
use chrono::Utc;
use cn_font_proto::api_interface::input_template::CssProperties;

pub fn create_header_comment(
    ctx: &mut Context<'_, '_, '_>,
    css: &CssProperties,
) -> String {
    let mut comment = String::new();

    if css.comment_base.unwrap_or(true) {
        let utc = Utc::now();
        comment.push_str(&format!(
            "Generated By cn-font-split@{} https://www.npmjs.com/package/cn-font-split\nCreateTime: {};\n",
            ctx.reporter.version,
            utc.to_rfc3339()
        ));
    }

    if css.comment_name_table.unwrap_or(true) {
        let name_table_comment = ctx
            .name_table
            .table
            .iter()
            .map(|x| {
                format!("{} {} {} {}", x.platform, x.language, x.name, x.value)
            })
            .collect::<Vec<String>>()
            .join("\n");
        comment.push_str(&name_table_comment);
    }

    if comment.is_empty() {
        return String::new();
    }
    format!("/* {}\n */\n\n", comment.trim())
}
