use crate::runner::Context;
use chrono::{DateTime, Utc};
use cn_font_proto::api_interface::input_template::CssProperties;
use cn_font_proto::api_interface::output_report;
use cn_font_utils::vec_u32_to_string;
use unicode_range::UnicodeRange;

pub fn output_css(ctx: &mut Context, css: &CssProperties) -> String {
    let name_table = &ctx.name_table;

    // fontData.preferredFamily  不使用这个，因为这个容易引起歧义
    let font_family = css.font_family.clone().unwrap_or_else(|| {
        name_table
            .get_name_first("FontFamilyName")
            .unwrap_or("default_font_family".to_string())
    });

    // 优先使用preferredSubFamily，如果没有，则使用fontSubFamily或fontSubfamily。
    // 提取字体样式
    let preferred_sub_family =
        name_table.get_name_first("FontSubfamilyName").unwrap_or_else(|| {
            name_table.get_name_first("FullFontName").unwrap_or("".to_string())
        });
    let font_style = css.font_style.clone().unwrap_or_else(|| {
        if is_italic(&preferred_sub_family) {
            "italic".to_string()
        } else {
            "normal".to_string()
        }
    });

    // 提取字体权重
    let font_weight = css.font_weight.clone().unwrap_or_else(|| {
        ctx.fvar_table
            .clone()
            .map(|x| x.vf_weight)
            .unwrap_or(get_weight(&preferred_sub_family).to_string())
    });

    // 生成本地字体声明
    let locals = if css.local_family.len() == 0 {
        vec![font_family.clone()]
    } else {
        css.local_family.clone()
    };
    let locals = locals
        .iter()
        .map(|x| format!("local(\"{x}\")"))
        .collect::<Vec<String>>();

    // 生成 polyfill 字符串
    let polyfill_str = css
        .polyfill
        .iter()
        .map(|p| format!(r#"url("{}") format("{}")"#, p.name, p.format))
        .collect::<Vec<String>>()
        .join(",");

    let display = css.font_display.clone().unwrap_or("swap".to_string());
    // 生成 @font-face 规则
    let codes = ctx
        .run_subset_result
        .iter()
        .rev()
        .map(|res| {
            let src_str = [
                locals.join(","),
                format!(r#"url("./{}")format("woff2")"#, res.file_name),
            ]
            .join(",")
                + &polyfill_str;
            let unicode_range = UnicodeRange::stringify(&res.unicodes);
            let space = if css.compress.unwrap_or(true) { "" } else { "    " };
            let face_code = format!(
                r#"@font-face{{
{space}font-family:"{font_family}";
{space}src:{src_str};
{space}font-style:{font_style};
{space}font-display:{display};
{space}font-weight:{font_weight};
{space}unicode-range:{unicode_range};
}}"#
            );
            let comment = if css.comment_unicodes.unwrap_or(false) {
                format!("/* {} */\n", vec_u32_to_string(&res.unicodes))
            } else {
                "".to_string()
            };
            let compressed = if css.compress.unwrap_or(true) {
                face_code.replace("\n", "")
            } else {
                face_code
            };
            comment + &compressed
        })
        .collect::<Vec<String>>();

    ctx.reporter.css = Some(output_report::Css {
        family: font_family.clone(),
        style: font_style.clone(),
        display: display.clone(),
        weight: font_weight.clone(),
    });

    let header_comment = create_header_comment(ctx, css);

    header_comment + &codes.join("")
}

fn create_header_comment(
    ctx: &mut Context<'_, '_, '_>,
    css: &CssProperties,
) -> String {
    let mut comment = String::new();

    if css.comment_base.unwrap_or(true) {
        let utc = Utc::now();
        comment.push_str(&format!(
            "Generated By cn-font-split@{} https://www.npmjs.com/package/cn-font-split\nCreateTime: {};\n",
            ctx.reporter.version,
            utc.to_rfc3339()
        ));
    }

    if css.comment_name_table.unwrap_or(true) {
        let name_table_comment = ctx
            .name_table
            .table
            .iter()
            .map(|x| {
                format!("{} {} {} {}", x.platform, x.language, x.name, x.value)
            })
            .collect::<Vec<String>>()
            .join("\n");
        comment.push_str(&name_table_comment);
    }

    if comment.is_empty() {
        return String::new();
    }
    format!("/* {}\n */\n\n", comment.trim())
}

pub fn get_weight(sub_family: &str) -> u32 {
    let sub_family = sub_family.to_ascii_lowercase();
    FONT_WEIGHT_NAME
        .binary_search_by_key(&sub_family.as_str(), |&(name, _)| name)
        .map_or(600, |idx| FONT_WEIGHT_NAME[idx].1)
}

/** 判断是否为斜体 */
fn is_italic(str: &str) -> bool {
    str.to_lowercase().contains("italic")
}

const FONT_WEIGHT_NAME: [(&str, u32); 15] = [
    ("thin", 100),
    ("hairline", 100),
    ("extra light", 200),
    ("ultra light", 200),
    ("extra bold", 800),
    ("ultra bold", 800),
    ("semi bold", 600),
    ("demi bold", 600),
    ("light", 300),
    ("normal", 400),
    ("regular", 400),
    ("medium", 500),
    ("bold", 700),
    ("heavy", 900),
    ("black", 900),
];
