name: Docker Image CI - cn-font-server

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'container'
                required: true
                default: 'cn-font-server:1.0.0'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to GHCR
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build the Docker image
              working-directory: ./packages/server
              run: docker build . --tag ghcr.io/${{github.actor}}/${{inputs.version}}

            - name: Push the Docker image
              run: docker push ghcr.io/${{github.actor}}/${{inputs.version}}
